export const mockProperties = [
  {
    id: 1,
    name: "Sunny Villa",
    price: 250000,
    location: "Miami, FL",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
    amenities: ["Pool", "Garden", "Garage", "Smart Home"],
    status: "Available",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2800,
    type: "House",
    vrTour: {
      enabled: true,
      panoramas: [
        {
          id: 1,
          name: "Living Room",
          url: "https://example.com/vr/living-room.jpg",
        },
        {
          id: 2,
          name: "Kitchen",
          url: "https://example.com/vr/kitchen.jpg",
        },
        // Add more panoramas for different rooms
      ],
    },
  },
  {
    id: 2,
    name: "Mountain Retreat",
    price: 180000,
    location: "Aspen, CO",
    image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800",
    amenities: ["Fireplace", "Ski-in/Ski-out", "Hot Tub", "Mountain View"],
    status: "Available",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2200,
    type: "Cabin",
  },
  {
    id: 3,
    name: "Urban Loft",
    price: 420000,
    location: "New York, NY",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
    amenities: ["Doorman", "Gym", "Roof Deck", "City View"],
    status: "Pending",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1500,
    type: "Apartment",
  },
  {
    id: 4,
    name: "Beachfront Condo",
    price: 550000,
    location: "San Diego, CA",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
    amenities: ["Ocean View", "Pool", "Fitness Center", "Parking"],
    status: "Available",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    type: "Condo",
  },
  {
    id: 5,
    name: "Country Estate",
    price: 850000,
    location: "Nashville, TN",
    image: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800",
    amenities: ["Acreage", "Horse Stables", "Guest House", "Pond"],
    status: "Available",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4500,
    type: "Estate",
  },
  {
    id: 6,
    name: "Modern Loft",
    price: 420000,
    location: "Chicago, IL",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
    amenities: ["Doorman", "Gym", "Roof Deck", "City View"],
    status: "Pending",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1500,
    type: "Apartment",
  },
  {
    id: 7,
    name: "Oceanview Condo",
    price: 550000,
    location: "Miami Beach, FL",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
    amenities: ["Ocean View", "Pool", "Fitness Center", "Parking"],
    status: "Available",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    type: "Condo",
  },
  {
    id: 8,
    name: "Luxury Estate",
    price: 850000,
    location: "Austin, TX",
    image: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?w=800",
    amenities: ["Acreage", "Horse Stables", "Guest House", "Pond"],
    status: "Available",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4500,
    type: "Estate",
  },
];

export const mockUsers = [
  {
    id: 1,
    name: "Admin User",
    email: "admin@gmail.com",
    role: "admin",
    password: "12345", // In real app, passwords should be hashed
  },
  {
    id: 2,
    name: "Test User 1",
    email: "user1@gmail.com",
    role: "user",
    password: "12345",
  },
  {
    id: 3,
    name: "Test User 2",
    email: "user2@gmail.com",
    role: "user",
    password: "12345",
  },
];

export const mockBookings = [
  {
    id: 1,
    propertyId: 1,
    propertyName: "Sunny Villa",
    clientId: 2,
    clientName: "Test User 1",
    date: "2024-10-25",
    time: "10:00",
    status: "Pending",
    createdAt: "2024-02-15",
    message: "Interested in viewing this property",
  },
  {
    id: 2,
    propertyId: 2,
    propertyName: "Mountain Retreat",
    clientId: 2,
    clientName: "Test User 1",
    date: "2024-10-25",
    time: "11:00",
    status: "Confirmed",
    createdAt: "2024-02-16",
    message: "Looking forward to seeing the property",
  },
  {
    id: 3,
    propertyId: 4,
    propertyName: "Beachfront Condo",
    clientId: 2,
    clientName: "Test User 2",
    date: "2024-10-25",
    time: "11:00",
    status: "Pending",
    createdAt: "2024-02-16",
    message: "Looking forward to seeing the property",
  },
];

export const mockBookingSlots = [
  {
    propertyId: 1,
    bookedSlots: [
      { date: "2024-10-25", time: "10:00" },
      { date: "2024-10-25", time: "11:00" },
      // Add more booked slots as needed
    ],
  },
  // Add more properties booking slots
];

// Add this helper function
export const timeSlots = [
  "09:00",
  "10:00",
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
];
